export const STORAGE_KEYS = {
  ACTION_ITEMS: 'll_action_items',
  STREAK_DATA: 'll_streak_data',
  BULK_IMPORT_SUMMARY: 'll_bulk_import_summary',
  ASKAI_HISTORY: 'll_askai_history',
  ASKAI_SESSION_INDEX: 'll_askai_session_index',
  ASKAI_SESSION_PREFIX: 'll_askai_session_',
  LAST_SR_ENROLL_DATE: 'll_last_sr_enroll_date',
  CHAT_HISTORY: 'll_chat_history',
  ONBOARDING_COMPLETED: 'll_onboarding_completed',
  ONBOARDING_PREFERENCES: 'll_onboarding_preferences',

  SCREENSHOT_ALBUM_ID: 'laterlens_screenshot_album_id',
  SCREENSHOT_ALBUM_TITLE: 'laterlens_screenshot_album_title',
  HAS_INITIAL_SCAN_COMPLETED: 'laterlens_has_initial_scan_completed',
  LAST_SCANNED_TIMESTAMP: 'laterlens_last_scanned_timestamp',
  GROQ_API_KEY: 'laterlens_groq_api_key',
  AI_MODE: 'laterlens_ai_mode',
  AUTO_PROCESSING_ENABLED: 'laterlens_auto_processing_enabled',
  WIFI_ONLY: 'laterlens_wifi_only',
  WATCHED_FOLDER_IDS: 'laterlens_watched_folder_ids',
  EXCLUSION_RULES: 'laterlens_exclusion_rules',
  DAILY_DIGEST_TIME: 'laterlens_daily_digest_time',
  NOTIFICATION_CONFIG: 'laterlens_notification_config',
  DAILY_DIGEST_NOTIFICATION_ID: 'll_daily_digest_notification_id',
  QUIET_HOURS: 'laterlens_quiet_hours',
  AUTO_ARCHIVE_DAYS: 'laterlens_auto_archive_days',
  PRIVACY_RULES: 'laterlens_privacy_rules',
  LIKELY_INDIAN_APP_FLAG: 'll_indian_app_flag',
};

export const LEGACY_STORAGE_KEYS = {
  ACTION_ITEMS: ['screenmind_action_queue_v1'],
  STREAK_DATA: ['streakData'],
  BULK_IMPORT_SUMMARY: ['lastBulkImportSummary', 'laterlens_last_bulk_import_summary'],
  ASKAI_HISTORY: ['askAI_history'],
  ASKAI_SESSION_INDEX: ['askAI_sessions_index'],
  ASKAI_SESSION_PREFIX: ['askAI_session_'],
  CHAT_HISTORY: ['@LaterLens:ChatHistory'],
  ONBOARDING_COMPLETED: ['hasCompletedOnboarding'],
  ONBOARDING_PREFERENCES: ['onboarding_preferences'],
};
